# Generated by Django 3.1.1 on 2021-01-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pistaspadel',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pistaspadel',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pistas.club'),
        ),
    ]
